sudo: required

services:
  - docker
  - xvfb

language: ruby
rvm:
  - 2.6.3
cache:
  bundler: true

addons:
  postgresql: "10"

before_install:
  - sudo sed -i '/ExecStart=\/usr\/bin\/dockerd -H fd:\/\//c\ExecStart=\/usr\/bin\/dockerd' /lib/systemd/system/docker.service
  - sudo systemctl daemon-reload
  - "echo '{\"hosts\": [\"tcp://127.0.0.1:2376\", \"unix:///var/run/docker.sock\"], \"iptables\": false}' | sudo tee /etc/docker/daemon.json  > /dev/null"
  - sudo service docker restart
  - sleep 5
  - docker pull openhpi/co_execenv_python
  - docker pull openhpi/co_execenv_java
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/docker.yml.erb.travis config/docker.yml.erb
  - psql --command='CREATE DATABASE travis_ci_test;' --username=postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - ./cc-test-reporter before-build

script: bundle exec rspec --color --format documentation --require spec_helper --require rails_helper

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
